core/urls.py
from django.urls import path
from . import views
from .views import login_site


urlpatterns = [
    path('home/', views.home, name='home'),
    path('index/', views.index, name='index'),
    
    path('logout/', views.logout_site, name='logout'),
    path('', views.login_site, name='login'),

    path('employee_list/', views.employee_list, name='employee_list'),
    path('employee_create/', views.employee_create, name='employee_create'),
    path('employee_edit/<int:employee_id>/', views.employee_edit, name='employee_edit'),
    path('employee_delete/<int:employee_id>/', views.employee_delete, name='employee_delete'),

    path('profile/<int:id>/', views.profile, name='profile'),

    path('course_create/', views.course_create, name='course_create'),
    path('course_list', views.course_list, name='course_list'),
    path('course_delete/<int:course_id>/delete', views.course_delete, name='course_delete'),
    path('course_edit/<int:course_id>/edit', views.course_edit, name = 'course_edit'),

    path('group_create/', views.group_create, name='group_create'),
    path('group_list/', views.group_list, name='group_list'),
    path('group_delete/<int:group_id>', views.group_delete, name='group_delete'),
    path('group_edit/<int:group_id>/', views.group_edit, name = 'group_edit'),

    path('student_create/', views.student_create, name='student_create'),
    path('student_list/', views.student_list, name='student_list'),
    path('student_delete/<int:student_id>', views.student_delete, name = 'student_delete'),
    path('student_edit/<int:student_id>/', views.student_edit, name='student_edit'),
    

    path('atendence/<str:code>/', views.attendance_create, name='atendence_create'),
    path('attendance_list/', views.attendance_list, name = 'attendance_list'),
    path('test/', views.create, name ='test'),
]

crm_course/urls.py
from django.contrib import admin
from django.urls import path , include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/models.py
from django.db import models
from django.urls import reverse
from django.contrib.auth.models import User
import qrcode
from .translit import translit_slug
from io import BytesIO
from PIL import Image , ImageDraw
from django.core.files import File
from django.utils.text import slugify
from django.http import HttpResponse
import csv
import os
from django.db.models.signals import post_delete
from django.dispatch import receiver

class Specialty(models.Model):
    specialty = models.CharField(max_length=100 , verbose_name='Специальность учителя')

    class Meta:
        verbose_name = 'Преподаватель'
        verbose_name_plural = 'Преподаватели'

    def __str__(self):
        return self.specialty


class Employee(models.Model):
    class EmployeeStatus(models.TextChoices):
        ADMINISTRATOR = 'admin', 'Администратор'
        TEACHER = 'teacher', 'Учитель'
    user = models.OneToOneField(User, verbose_name='Пользователь', on_delete=models.CASCADE)
    position = models.CharField(choices=EmployeeStatus.choices, max_length=20, verbose_name='Должность')
    phone = models.CharField(verbose_name='Номер телефона', max_length=20, null=True, blank=True)
    specialty = models.ForeignKey(Specialty, verbose_name='Специальность', on_delete=models.CASCADE)

    class Meta:
        verbose_name = 'Сотрудник'
        verbose_name_plural = 'Сотрудники'

    def __str__(self):
        return self.user.username
    
class Course(models.Model):
    class CourseStatus(models.TextChoices):
        ACTIVE = 'active', 'Активный'
        INACTIVE = 'inactive', 'Неактивный'
    name = models.CharField(max_length=100, verbose_name='Курс обучения')
    description = models.TextField()
    price = models.CharField(max_length=100 ,verbose_name='Цена')
    status = models.CharField(choices=CourseStatus.choices, max_length=20, verbose_name='Статус')

    class Meta:
        verbose_name = 'Курс'
        verbose_name_plural = 'Курсы'

    def __str__(self):
        return self.name

class Student(models.Model):
    class StudentStatus(models.TextChoices):
        ACTIVE = 'active' , 'Активный'
        ARCHIVED = 'archived', 'Архивный'
    user = models.OneToOneField(User, verbose_name='Пользователь', on_delete=models.CASCADE)
    status = models.CharField(choices=StudentStatus.choices,  max_length=20, verbose_name='Статус')
    phone = models.CharField(max_length=255, verbose_name='Номер телефона')
    qr_code = models.ImageField(upload_to= 'students_qr/', blank=True)
    code = models.CharField(max_length=20, blank=True)


    class Meta:
        verbose_name = 'Ученик'
        verbose_name_plural = 'Ученики'

    def __str__(self):
        return self.user.username
    
    def save(self, *args, **kwargs):
        if self.pk:
            old_student = Student.objects.get(pk=self.pk)
            if old_student.qr_code:
                os.remove(old_student.qr_code.path)
                old_student.qr_code.delete(save=False)
        code = translit_slug()
        qrcode_img = qrcode.make(f"http://127.0.0.1:8000/atendence/{code}")
        canvas = Image.new('RGB', (350, 350), 'white')
        draw = ImageDraw.Draw(canvas)
        canvas.paste(qrcode_img)
        fname = f'qr_code-{code}.png'
        buffer = BytesIO()
        canvas.save(buffer, 'PNG')
        self.qr_code.save(fname, File(buffer), save=False)
        self.code = code
        canvas.close()
        super().save(*args, **kwargs)

@receiver(post_delete, sender=Student)
def delete_qr_code(sender, instance, **kwargs):
        if instance.qr_code:
            instance.qr_code.delete(False)

 
class Group(models.Model):
    name = models.CharField(max_length=100 , verbose_name = 'Название группы')
    employee = models.ForeignKey(Employee, on_delete=models.CASCADE, verbose_name = 'Преподаватель')
    course = models.ForeignKey(Course, on_delete=models.CASCADE, verbose_name = 'Курс')
    students = models.ManyToManyField(Student , verbose_name= 'Ученики')
    date_start = models.DateField(verbose_name='Дата начала подписки', null = True)
    date_end = models.DateField(verbose_name='Дата конца подписки', null=True)

    class Meta:
        verbose_name = 'Группа'
        verbose_name_plural = 'Группы'

    def __str__(self):
        return self.name

class Attendance(models.Model):
    student = models.ForeignKey(Student, on_delete=models.CASCADE, null = True)
    date = models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name = 'Посещаемость'
        verbose_name_plural = 'Посещаемость'
    

class Transaction(models.Model):
    amount = models.DecimalField(max_digits=10, decimal_places=2)
    date = models.DateField()
    employee = models.ForeignKey(Employee, on_delete=models.CASCADE, null = True)
    is_income = models.BooleanField(default=True) 
    student = models.ForeignKey(Student, on_delete=models.CASCADE, null = True)
    course = models.ForeignKey(Course, on_delete=models.CASCADE, null = True)

core/views.py
from django.shortcuts import render, reverse, redirect, get_object_or_404
from .forms import CourseForm
from .models import Course, Specialty, Student , Employee , Group, Attendance
from django.contrib.auth import authenticate , login , logout
from django.contrib.auth.decorators import login_required
from django.contrib.admin.views.decorators import staff_member_required
from .forms import CourseForm,  EmployeeCreationForm , StudentForm
import qrcode
from datetime import datetime
from django.core.paginator import Paginator , EmptyPage, PageNotAnInteger
from .models import  Course
from django.contrib.auth.models import User
from django.utils import timezone
from django.utils.text import slugify
from django.core.files.storage import FileSystemStorage
from random import randint
from django.contrib.auth.decorators import user_passes_test

# @staff_member_required Нужен для того чтобы добавлять ученика или курс мог только администратор !!!!

@login_required
def index(request):
    if request.user.is_authenticated:
        employees = Employee.objects.all()
        employeechoices = Employee.EmployeeStatus.choices
        courses = Course.objects.all()
        specialties = Specialty.objects.all()
        context = {'courses': courses ,'employees': employees ,'employeechoices': employeechoices, 'specialties': specialties}
        return render(request, 'index.html', context)
    return redirect('index')

def home(request):
    courses = Course.objects.all()
    return render(request, 'home.html', {'courses': courses})

# Авторизация
def login_site(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            return redirect('home')
        else:
            return render(request, 'base.html', {'error_message': 'Неверное имя пользователя или пароль.'})
    return render(request, 'base.html')

@login_required
def logout_site(request):
    logout(request)
    return redirect('login')
# -----------------------------

# Профиль 
def profile(request, id):
    profile = Employee.objects.get(user_id__exact = id)
    return render(request, 'profile.html', {'profile': profile})
# --------------------------

# Создание
@staff_member_required
def employee_create(request):
    if request.method == 'POST':
        form = EmployeeCreationForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('employee_list')
    else:
        form = EmployeeCreationForm()
    return render(request, 'employee_create.html', {'form': form})

@staff_member_required
def course_create(request):
    if request.method == 'POST':
        form = CourseForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('course_list')
    else:
        form = CourseForm()
    return render(request, 'course_create.html', {'form': form})

@staff_member_required
def group_create(request):
    if request.method == 'POST':

        name = request.POST.get('name')
        employee = request.POST.get('employee')
        course = request.POST.get('course')
        students = request.POST.getlist('students')
        date_start = request.POST.get('date_start')
        date_end = request.POST.get('date_end')

        date_start = datetime.strptime(date_start, '%Y-%m-%d')
        date_end = datetime.strptime(date_end, '%Y-%m-%d')

        group = Group.objects.create(
            name=name,
            employee=Employee.objects.get(pk=employee),
            course=Course.objects.get(pk=course),
            date_start=date_start,
            date_end=date_end
        )
        group.students.add(*students)
        return redirect('group_list')
    else:
        employees = Employee.objects.all()
        students = Student.objects.all()
        courses = Course.objects.all()
        context = {
            'employees': employees,
            'students': students,
            'courses': courses
        }
        return render(request, 'group_create.html', context)
    
@staff_member_required
def student_create(request):
    if request.method == 'POST':
        form = StudentForm(request.POST)
        if form.is_valid():
            user = User.objects.create_user(
                username=form.cleaned_data['username'],
                first_name=form.cleaned_data['first_name'],
                last_name=form.cleaned_data['last_name'],
                password=form.cleaned_data['password']
            )

            student = form.save(commit=False)
            student.user = user
            student.save()
            return redirect('student_list')
    else:
        form = StudentForm()
    return render(request, 'student_create.html', {'form': form})
# ---------------------------------------------

# Списки
def employee_list(request):
    employees = Employee.objects.all()
    return render(request, 'employee_list.html', {'employees': employees})

def group_list(request):
    groups = Group.objects.all()
    return render(request, 'group_list.html', {'groups': groups})

def course_list(request):
    courses = Course.objects.all()
    return render(request, 'course_list.html', {'courses': courses})

def student_list(request):
    students = Student.objects.all()
    return render(request, 'student_list.html', {'students': students})
# --------------------------------------------

# Удаление
@staff_member_required
def employee_delete(request, employee_id):
    employee = get_object_or_404(Employee, id=employee_id)
    if request.method == 'POST':
        employee.delete()
        return redirect('employee_list')
    
@staff_member_required
def course_delete(request, course_id):
    course = get_object_or_404(Course, id=course_id)
    if request.method == 'POST':
        course.delete()
        return redirect('course_list')
    
@staff_member_required
def group_delete(request , group_id ):
    group = get_object_or_404(Group , id=group_id)
    if request.method == 'POST':
        group.delete()
        return redirect('group_list')
    
@staff_member_required
def student_delete(request, student_id):
    student = get_object_or_404(Student, id=student_id)
    if request.method == 'POST':
        student.delete()
        return redirect('student_list')
# -------------------------------------------

# Изменение
@staff_member_required
def employee_edit(request, employee_id):
    employee = Employee.objects.get(pk=employee_id)
    if request.method == 'POST':
        first_name = request.POST['first_name']
        last_name = request.POST['last_name']
        phone = request.POST['phone']
        specialty_id = request.POST['specialty']
        position = request.POST['position']
        user = employee.user
        user.first_name = first_name
        user.last_name = last_name
        user.save()
        employee.phone = phone
        employee.specialty = Specialty.objects.get(pk=specialty_id)
        employee.position = position
        employee.save()
        return redirect('employee_list')
    else:
        specialties = Specialty.objects.all()
        context = {
            'employee': employee,
            'specialties': specialties,
        }
        return render(request, 'employee_edit.html', context)
  
@staff_member_required
def course_edit(request, course_id):
    course = get_object_or_404(Course, id=course_id)
    if request.method == 'POST':
        name = request.POST.get('name')
        price = request.POST.get('price')
        description = request.POST.get('description')
        status = request.POST.get('status')
        course.name = name
        course.price = price
        course.description = description
        course.status = status
        course.save()
        return redirect('course_list')
    return render(request, 'course_edit.html', {'course': course})

@staff_member_required    
def group_edit(request, group_id):
    group = get_object_or_404(Group, pk=group_id)
    if request.method == 'POST':
        group.name = request.POST.get('name')
    
        employee_id = request.POST.get('employee')
        employee = get_object_or_404(Employee, pk=employee_id)
        group.employee = employee
    
        course_id = request.POST.get('course')
        course = get_object_or_404(Course, pk=course_id)
        group.course = course
        
        group.students.set(request.POST.getlist('students'))
        group.date_start = request.POST.get('date_start')
        group.date_end = request.POST.get('date_end')
        group.save()
        return redirect('group_list')
    else:
        employees = Employee.objects.all()
        students = Student.objects.all()
        courses = Course.objects.all()
        context = {
            'group': group,
            'employees': employees,
            'students': students,
            'courses': courses
        }
        return render(request, 'group_edit.html', context)
    
def student_edit(request, student_id):
    student = Student.objects.get(pk=student_id)
    if request.method == 'POST':
        first_name = request.POST['first_name']
        last_name = request.POST['last_name']
        status = request.POST['status']
        phone = request.POST['phone']
        user = student.user
        user.first_name = first_name
        user.last_name = last_name
        user.save()
        student.phone = phone
        student.status = status
        student.save()
        return redirect('student_list')
    return render(request, 'student_edit.html', {'student': student})
# ----------------------------------

# Посещаемость
def attendance_list(request):
    attendances = Attendance.objects.all()
    sort_by = request.GET.get('sort_by')
    if sort_by == 'old_to_new':
        attendances = attendances.order_by('date')
    elif sort_by == 'new_to_old':
        attendances = attendances.order_by('-date')

core/templates/attendance_list.html
{% extends 'index.html' %}
{% block content %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=, initial-scale=1.0">
    <title>Посещаемось</title>
</head>
<body>
  <style>
.table {
  margin-top: 75px;
	width: 100%;
	border: none;
	margin-bottom: 20px;
	border-collapse: separate;
}
.table thead th {
	font-weight: bold;
	text-align: left;
	border: none;
	padding: 10px 15px;
	background: #EDEDED;
	font-size: 14px;
	border-top: 1px solid #ddd;
}
.table tr th:first-child, .table tr td:first-child {
	border-left: 1px solid #ddd;м
}
.table tr th:last-child, .table tr td:last-child {
	border-right: 1px solid #ddd;
}
.table thead tr th:first-child {
	border-radius: 20px 0 0 0;
}
.table thead tr th:last-child {
	border-radius: 0 20px 0 0;
}
.table tbody td {
	text-align: left;
	border: none;
	padding: 10px 15px;
	font-size: 14px;
	vertical-align: top;
}
.table tbody tr:nth-child(even) {
	background: #F8F8F8;
}
.table tbody tr:last-child td{
	border-bottom: 1px solid #ddd;
}
.table tbody tr:last-child td:first-child {
	border-radius: 0 0 0 20px;
}
.table tbody tr:last-child td:last-child {
	border-radius: 0 0 20px 0;
}
  </style>
<table class="table">
  <thead>
      <tr>
          <th>Имя ученика</th>
          <th>Фамилия ученика</th>
          <th>Время посещения</th>
      </tr>
  </thead>
  <tbody>
      {% for attendance in attendances %}
      <tr>
          <td>{{ attendance.student.user.first_name }}</td>
          <td>{{ attendance.student.user.last_name }}</td>
          <td>{{ attendance.date }}</td>
      </tr>
      {% endfor %}
  </tbody>
</table>

<!-- Навигация по страницам -->
<nav aria-label="Page navigation example">
  <ul class="pagination" style="display: flex; justify-content: center;">
    {% if attendances.has_previous %}
    <li class="page-item">
      <a class="page-link" href="?page=1" aria-label="First">
        <span aria-hidden="true">&laquo;&laquo;</span>
      </a>
    </li>
    <li class="page-item">
      <a class="page-link" href="?page={{ attendances.previous_page_number }}" aria-label="Previous">
        <span aria-hidden="true">&laquo;</span>
      </a>
    </li>
    {% endif %}

    {% for page_num in attendances.paginator.page_range %}
    <li class="page-item {% if page_num == attendances.number %}active{% endif %}">
      <a class="page-link" href="?page={{ page_num }}">{{ page_num }}</a>
    </li>
    {% endfor %}

    {% if attendances.has_next %}
    <li class="page-item">
      <a class="page-link" href="?page={{ attendances.next_page_number }}" aria-label="Next">
        <span aria-hidden="true">&raquo;</span>
      </a>
    </li>
    <li class="page-item">
      <a class="page-link" href="?page={{ attendances.paginator.num_pages }}" aria-label="Last">
        <span aria-hidden="true">&raquo;&raquo;</span>
      </a>
    </li>
    {% endif %}
  </ul>
</nav>
</body>
</html>
{% endblock %}

core/templates/employee_create.html
{% extends 'index.html' %}
{% block content %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Создания сотрудника</title>
    
</head>
<body>
    <div class="new-users">
        <h2>Создание сотрудника</h2>
        <div class="user-list">

        <div class="course-title">



                    <form class="" method="POST">
                        
                        {% csrf_token %}
                        {{ form.as_p }}
                       
                        <button class="btn-outline-sm" type="submit">Создать</button>
                    </form>
                </div> <input >
                
	
            </div>
        </div>
    </div>

    
</body>
</html>
{% endblock %}

core/templates/employee_list.html
{% extends 'index.html' %}
{% block content %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>
<body>
<div class="new-users">
    <div class="user-list">
        <table>
            <thead>
                <tr>
                    <th>Имя</th>
                    <th>Фамилия</th>
                    <th>Номер телефона</th>
                    <th>Должность</th>
                </tr>
            </thead>
            <tbody>
                {% for employee in employees %}
                <tr>
                    <td> <a href="{% url 'profile' request.user.id %}"> {{ employee.user.first_name }}</a></td>
                    <td>{{ employee.user.last_name }}</td>
                    <td>{{ employee.phone }}</td>
                    <td>{{ employee.get_position_display }}</td>
                    <td>
                        <button type="button" class="delete-button" data-modal-id="modal{{ employee.id }}">Удалить</button>
                    </td>
                    <td><a href="{% url 'employee_edit' employee.id %}" class="edit-button">Изменить</a></td>
                </tr>
                {% endfor %}
            </tbody>

        </table>
    </div>
</div>
{% for employee in employees %}
                
                <div id="modal{{ employee.id }}" class="modal">
                    <form action="{% url 'employee_delete' employee.id %}" method="POST">
                        {% csrf_token %}
                        <div class="modal-content">
                            <span class="close">&times;</span>
                            <p>Вы действительно хотите удалить учителя {{ employee.user.first_name }} {{ employee.user.last_name }}?</p>
                            
                            <button>Удалить</button>
                        </div>
                    </form>
                    
                </div>
                {% endfor %}
</body>
</html>
{% endblock %}

core/templates/index.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    
    
        <!-- Картинка вкладки -->
        <link rel="icon" href="{% static 'images/favicon.png' %}">  

    <link href="https://fonts.googleapis.com/icon?family=Material+Icons+Sharp" rel="stylesheet">
 
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/style.css'%}">  

    <title>{% block title %} CRM PROGRESS {% endblock %}</title>
</head>
<body>

    {% if not request.user.is_authenticated %}
    <p style="text-align: center; text-align: center;">Вы не вошли в аккаунт</p>
    {% else %}
    <div class="container-custom">
        <!-- Sidebar Section -->
        <aside>
            <div class="toggle">
                <div class="logo-custom">
                    <h2><b>CRM</b><span class="danger"> <br><b>Progress</b></span></h2>
                </div>
                <div class="close" id="close-btn">
                    <span class="material-icons-sharp">
                        close
                    </span>
                </div>
            </div>

            <div class="sidebar-custom">
                <a href="{% url 'home' %}" {% if request.path == '/' %} class="active" {% endif %}>
                    <span class="material-icons-sharp">
                        dashboard
                    </span>
                    <h3>Главная</h3>
                </a>
                

                <a href="{% url 'profile' request.user.id %}" {% if "profile/" in request.path and request.path|slice:'9:' %} class="active" {% endif %}>
                    <span class="material-icons-sharp">
                        person
                    </span>
                    <h3>Профиль</h3>
                </a>
                    <a href="{% url 'course_list' %}" {% if request.path == '/course_list' %} class="active" {% endif %}>
                        <span class="material-icons-sharp">
                            <i class="fa-solid fa-book"></i>
                        </span>
                        <h3>Курсы</h3>
                    </a>
                    {% if user.is_superuser %}
                    
             
                <a href="{% url 'employee_create' %}" {% if request.path == '/employee_create/' %} class="active" {% endif %}>
                    <span class="material-icons-sharp">
                        add
                    </span>
                    <h3>Добавить <br>аккаунт</h3>
                </a>

                <a href="{% url 'attendance_list' %}" {% if request.path == '/employee_create/' %} class="active" {% endif %}>
                    <span class="material-icons-sharp">
                        add
                    </span>
                    <h3>СПИСОК </h3>
                </a>
                <a href="{% url 'course_create' %}" {% if request.path == '/course_create/' %} class="active" {% endif %}>
                    <span class="material-icons-sharp">
                        add
                    </span>
                    <h3>Создания <br>курса</h3>
                </a>
                <a href="{% url 'group_create' %}" {% if request.path == '/group_create/' %} class="active" {% endif %}>
                    <span class="material-icons-sharp">
                        add
                    </span>
                    <h3>Создание <br>группы</h3>
                </a>
                <a href="{% url 'student_create' %}" {% if request.path == '/student_create/' %} class="active" {% endif %}>
                    <span class="material-icons-sharp">
                        
                    </span>
                    <h3>Создание <br>студента</h3>
                </a>
                
                <a href="{% url 'employee_list' %}" {% if request.path == '/employee_list/' %} class="active" {% endif %}>
                    <span class="material-icons-sharp">
                        person
                    </span>
                    <h3>Сотрудники</h3>
                </a>
                <a href="{% url 'group_list' %}" {% if request.path == '/group_list/' %} class="active" {% endif %}>
                    <span class="material-icons-sharp">
                        person_outline
                    </span>
                    <h3>Группы</h3>
                </a>
                <a href="http://127.0.0.1:8000/admin">
                    <span class="material-icons-sharp">
                        settings
                    </span>
                    <h3>Админка</h3>
                </a>
                {% endif %}

                <a href="{% url 'logout' %}">
                    <span class="material-icons-sharp">
                        logout
                    </span>
                    <h3>Выйти из акк</h3>
                </a>
                
            </div>
        </aside>
        <!-- End of Sidebar Section -->

        <!-- Main Content -->
       



    
            <main>
                {% block content %}{% endblock %}
            </main>
            

                    <!-- Right Section -->
        <div class="right-section-custom">
            <div class="nav-custom">
                <button id="menu-btn">
                    <span class="material-icons-sharp">
                        menu
                    </span>
                </button>
                <div class="dark-mode">
                    <span class="material-icons-sharp active">
                        light_mode
                    </span>
                    <span class="material-icons-sharp">
                        dark_mode
                    </span>
                </div>

                <div class="profile">
                    <div class="info">
                        <p>Привет, <b>{{user.first_name}}</b></p>
                        <small class="text-muted"></small>
                    </div>
                </div>
 
            </div>
            <!-- End of Nav -->

            <div class="user-profile-custom">
                <div class="logo-custom">

                    <h2>{{ user.first_name }} {{ user.last_name }}</h2>

                {% if user.employee %}

                    <p>Должность: {{ user.employee.get_position_display }}</p>
                    <p>Номер телефона: {{user.employee.phone}}</p>

                    {% else %}
                    <p>Номер телефона: {{user.student.phone}}</p>

                {% endif %}
                </div>
            </div>

    </div>
    {% endif%}
    <script src="{% static 'js/script.js' %}"></script>
    <script src="{% static 'js/index.js' %}"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.6/dist/umd/popper.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.min.js"></script>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
<script src="https://kit.fontawesome.com/af02ed48ba.js" crossorigin="anonymous"></script>
</body>

</html>

core/templates/profile.html
{% extends 'index.html' %}
{% block title %} Профиль {% endblock %}
{% block content %}
<div class="new-users">
<div class="user-list">
    <h1>{{ user.username }}</h1>
    <h2>{{ user.first_name }} {{ user.last_name }}</h2>

    <p>Номер телефона: {{ user.employee.phone }}</p>
    
    <p>Должность: {{ user.employee.get_position_display }}</p>
    
</div>
</div>
<br>
{% endblock %}  

core/templates/register.html
{% extends 'index.html' %}
{% block content %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Registration</title>
</head>
<body>
    <h2>User Registration</h2>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Register</button>
    </form>
</body>
</html>
{% endblock %}